name: Install .NET Tool - Sonar Scanner
description: Install the latest version of Sonar Scanner using dotnet tool.
inputs:
  version:
    description: The version of Sonar Scanner to install.
    required: false
runs:
  using: composite
  steps:
  - run: |
      if [ -n "${{ inputs.version }}" ]; then
        dotnet tool update --global dotnet-sonarscanner --version "${{ inputs.version }}"
      else
        dotnet tool update --global dotnet-sonarscanner
      fi
    shell: bash
branding:
  icon: 'umbrella'
  color: 'blue'
